name: Configure AWS Credentials
description: Configures AWS credentials using OIDC
inputs:
  aws-region:
    description: AWS region
    required: true
  role-arn:
    description: IAM role ARN to assume
    required: true
  session-name:
    description: Role session name
    required: false
    default: github-actions-session
runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.role-arn }}
        role-session-name: ${{ inputs.session-name }}-${{ github.run_id }}
        aws-region: ${{ inputs.aws-region }}
